version: '3.1'
services:
  system:
    build:
      context: ./mysql
    container_name: mysql8
    command: --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_RANDOM_ROOT_PASSWORD=false
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306" # 设置容器3306端口映射指定宿主机端口
    restart: always

#     networks:
#       - base_env
# networks:
#   base_env:
#     external: true
