version: '3.1'
services:
  system:
    build:
      context: ./mysql
    container_name: mysql8
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306" # 设置容器3306端口映射指定宿主机端口
    restart: always
