version: '3.1'
services:
  system:
    build:
      context: ./redis
    container_name: redis
    ports:
      - "6379:6379" # 设置容器3306端口映射指定宿主机端口
    restart: always

    networks:
      - base_env
networks:
  base_env:
    external: true
